name: Make Rebuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar herramientas necesarias
        run: sudo apt update && sudo apt install -y nasm gcc make qemu-system-x86

      - name: Ejecutar `make re`
        run: make clean all

      - name: Qemu
        run: qemu-system-x86_64 -drive format=raw,file=build/os.img -nographic -serial mon:stdio -no-reboot -m 512
       
#      - name: Subir os.bin
#        uses: actions/upload-artifact@v4
#        with:
#          name: os-bin
#          path: build/os.bin
